name: Download, build and publish NVD cache
on:
  schedule:
    - cron:  '0 13,23 * * *'
  workflow_dispatch:
  # Needed so we can run it manually

jobs:
  build:
    permissions:
      contents: write
    name: Update NVD API Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
          ref: gh-pages
      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: update
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          curl https://github.com/jeremylong/open-vulnerability-cli/releases/download/v9.0.4/vulnz-9.0.4.jar -s -L -o vulnz.jar
          git reset --soft HEAD~1
          ls -la .
          java -Xmx4g -jar vulnz.jar cve --cache --directory ./nvd_cache  --requestCount=30 --debug --delay=8000 --maxRetry=40
          rm vulnz.jar
          last_generated=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          last_updated=$(sed -n 's/^lastModifiedDate=//p' nvd_cache/cache.properties | sed 's/\\:/:/g')
          sed -e "s/@@LAST_GENERATED@@/${last_generated}/" -e "s/@@LAST_UPDATED@@/${last_updated}/" index.html.template > index.html
          git status
          cat nvd_cache/cache.properties
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add ./nvd_cache/
          git commit -am 'chore: update'
          git push origin gh-pages --force
          cat nvd_cache/nvdcve-modified.meta


  deploy-pages:
    needs: build
    permissions:
      pages: write
      id-token: write
      contents: read
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          name: github-pages-${{ github.run_attempt }}
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
        with:
          artifact_name: github-pages-${{ github.run_attempt }}
