name: Deploy runners

on:
  workflow_call:
    inputs:      
      environment:
        description: The name of the environment to deploy to (dev/prod)
        type: string
        required: true
      version:
        description: The image version to deploy
        type: string
        required: true

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - production
        default: production
      version:
        description: Image version
        type: string
        required: true
        default: 'latest-prod'

jobs:
  deploy:
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}  
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/get-env-details
        id: env
        with:
          environment: ${{ inputs.environment }}

      - name: Deploy to Platform
        uses: ./.github/actions/cloud-platform-deploy
        with:
          version: ${{ inputs.version }}
          api: https://${{ secrets.KUBE_CLUSTER }}
          cert: ${{ secrets.KUBE_CERT }}
          cluster: ${{ secrets.KUBE_CLUSTER }}
          namespace: ${{ secrets.KUBE_NAMESPACE }}
          token: ${{ secrets.KUBE_TOKEN }}   
          github_org: ${{ github.repository_owner }}
          runner_label: ${{ vars.RUNNER_LABEL }}
          runner_group: ${{ vars.RUNNER_GROUP }}
