name: Remove offline runners

on:
  workflow_call:

jobs:
  remove-offline-runners:
    runs-on: ubuntu-latest
    name: Remove offline runners
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: GitHub app installation access token generation
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: generate-github-app-tokens
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
        owner: ministryofjustice
    - name: runner cleanup
      uses: ./.github/actions/runner-cleanup
      with:
        gh_auth_token: ${{ steps.generate-github-app-tokens.outputs.token }}
        github_org: ${{ github.repository_owner }}
        runner_label: ${{ vars.RUNNER_LABEL }}
